name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.8
      
      - name: Set up working directory and run Make commands
        run: |
          chmod +x app/gradlew 
          #cd $GITHUB_WORKSPACE/app
          #chmod +x ./gradlew  # Добавляем разрешения на выполнение
          make setup
          make clean
          make build
          make install
          make lint
          make build

      - name: Generate coverage report
        run: |
          #cd $GITHUB_WORKSPACE/app
          make report
        
      - name: Show Jacoco report snippet
        run: |
          echo "=== Jacoco Report Preview ==="
          head -n 20 app/build/reports/jacoco/test/jacocoTestReport.xml
          echo "============================="
          
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: app/src/main/java  # Путь к исходникам
        with:
          coverageCommand: make report  # Явно указываем команду для генерации отчета
          coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          coverageInputType: jacoco
          debug: true